services:
  nuxt-app:
    image: hymns-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=${BACKEND_URL}
    restart: unless-stopped
