services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hymns-backend
    restart: unless-stopped
    environment:
      - RPUNCT_URL=http://rpunct:8000
    ports:
      - "3100"
    volumes:
      - db_data:/app/src/data

  rpunct:
    build:
      context: ./rpunct_service
      dockerfile: Dockerfile
    container_name: hymns-rpunct
    restart: unless-stopped
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hymns-frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://hymns-backend:3100
      - NUXT_PUBLIC_API_URL=https://hymns-back.jville.dev
    ports:
      - "3000"
    depends_on:
      - backend

volumes:
  db_data: