services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3100:3100"
    volumes:
      - db_data:/app/src/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - BACKEND_URL=http://backend:3100
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data: